<?php

namespace morphos;

//function recursiveCrazyImport($file)
//{
//    try {
//        include $file;
//    } catch (Error $e) {
//        $errorMsg = $e->getMessage();
//        $missingFile = preg_match('/"(.*)"/', $errorMsg, $matches);
//        $missingFile = trim($matches[0], '"');
//        $res = str_replace('morphos\\', '', $missingFile);
//        var_dump($res);
//        recursiveCrazyImport($missingFile);
//    }
//}

set_include_path(get_include_path()
    . PATH_SEPARATOR . '../src'
    . PATH_SEPARATOR . '../src/Russian'
);

spl_autoload_register(function ($className) {
    $t = str_replace('morphos\\', "", $className);
    require_once $t . '.php';
});


// RENDER FUNCTION
function renderTemplate($tmp, $vars = array())
{
    if (file_exists('templates/' . $tmp . '.tpl.php')) {
        ob_start();
        extract($vars);
        require 'templates/' . $tmp . '.tpl.php';
        return ob_get_clean();
    }
}

// echo render('index', array('cityNameRus' => $cityNameRus));
/* 'moscow' => 'Москва'
СКЛОНЕНИЯ!!! БЛЯЯЯЯ
2 предложных один именительный Нижний Новгород в Нижнем Новгороде
*/
$cityNamesRus = ["Москва",
    "Санкт-Петербург",
    "Новосибирск",
    "Екатеринбург",
    "Казань",
    "Нижний Новгород",
    "Челябинск",
    "Красноярск",
    "Самара",
    "Уфа",
    "Ростов-на-Дону",
    "Омск",
    "Краснодар",
    "Воронеж",
    "Пермь",
    "Волгоград",
    "Саратов",
    "Тюмень",
    "Тольятти",
    "Барнаул",
    "Ижевск",
    "Махачкала",
    "Хабаровск",
    "Ульяновск",
    "Иркутск",
    "Владивосток",
    "Ярославль",
    "Кемерово",
    "Томск",
    "Набережные Челны",
    "Севастополь",
    "Ставрополь",
    "Оренбург",
    "Новокузнецк",
    "Рязань",
    "Балашиха",
    "Пенза",
    "Чебоксары",
    "Липецк",
    "Калининград",
    "Астрахань",
    "Тула",
    "Киров",
    "Сочи",
    "Курск",
    "Улан-Удэ",
    "Тверь",
    "Магнитогорск",
    "Сургут",
    "Брянск",
    "Иваново",
    "Якутск",
    "Владимир",
    "Симферополь",
    "Белгород",
    "Нижний Тагил",
    "Калуга",
    "Чита",
    "Грозный",
    "Волжский",
    "Смоленск",
    "Подольск",
    "Саранск",
    "Вологда",
    "Курган",
    "Череповец",
    "Орёл",
    "Архангельск",
    "Владикавказ",
    "Нижневартовск",
    "Йошкар-Ола",
    "Стерлитамак",
    "Мурманск",
    "Кострома",
    "Новороссийск",
    "Тамбов",
    "Химки",
    "Мытищи",
    "Нальчик",
    "Таганрог",
    "Нижнекамск",
    "Благовещенск",
    "Комсомольск-на-Амуре",
    "Петрозаводск",
    "Королёв",
    "Шахты",
    "Энгельс",
    "Великий Новгород",
    "Люберцы",
    "Братск",
    "Старый Оскол",
    "Ангарск",
    "Сыктывкар",
    "Дзержинск",
    "Псков",
    "Орск",
    "Красногорск",
    "Армавир",
    "Абакан",
    "Балаково",
    "Бийск",
    "Южно-Сахалинск",
    "Одинцово",
    "Уссурийск",
    "Прокопьевск",
    "Рыбинск",
    "Норильск",
    "Волгодонск",
    "Сызрань",
    "Петропавловск-Камчатский",
    "Каменск-Уральский",
    "Новочеркасск",
    "Альметьевск",
    "Златоуст",
    "Северодвинск",
    "Хасавюрт",
    "Керчь",
    "Домодедово",
    "Салават",
    "Миасс",
    "Копейск",
    "Пятигорск",
    "Электросталь",
    "Майкоп",
    "Находка",
    "Березники",
    "Коломна",
    "Щёлково",
    "Серпухов",
    "Ковров",
    "Нефтекамск",
    "Кисловодск",
    "Батайск",
    "Рубцовск",
    "Обнинск",
    "Кызыл",
    "Дербент",
    "Нефтеюганск",
    "Назрань",
    "Каспийск",
    "Долгопрудный",
    "Новочебоксарск",
    "Новомосковск",
    "Ессентуки",
    "Невинномысск",
    "Октябрьский",
    "Раменское",
    "Первоуральск",
    "Михайловск",
    "Реутов",
    "Черкесск",
    "Жуковский",
    "Димитровград",
    "Пушкино",
    "Артём",
    "Камышин",
    "Евпатория",
    "Муром",
    "Ханты-Мансийск",
    "Новый Уренгой",
    "Северск",
    "Орехово-Зуево",
    "Арзамас",
    "Ногинск",
    "Новошахтинск",
    "Бердск",
    "Элиста",
    "Сергиев Посад",
    "Видное",
    "Ачинск",
    "Тобольск",
    "Ноябрьск"];
$cityNamesLatin = ["Moskva",
    "Sankt-Peterburg",
    "Novosibirsk",
    "Ekaterinburg",
    "Kazan",
    "Nizhniy-Novgorod",
    "Chelyabinsk",
    "Krasnoyarsk",
    "Samara",
    "Ufa",
    "Rostov-na-Donu",
    "Omsk",
    "Krasnodar",
    "Voronezh",
    "Perm",
    "Volgograd",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Barnaul",
    "Izhevsk",
    "Mahachkala",
    "Habarovsk",
    "Ulyanovsk",
    "Irkutsk",
    "Vladivostok",
    "Yaroslavl",
    "Kemerovo",
    "Tomsk",
    "Naberezhnye-Chelny",
    "Sevastopol",
    "Stavropol",
    "Orenburg",
    "Novokuzneck",
    "Ryazan",
    "Balashiha",
    "Penza",
    "Cheboksary",
    "Lipeck",
    "Kaliningrad",
    "Astrahan",
    "Tula",
    "Kirov",
    "Sochi",
    "Kursk",
    "Ulan-Ude",
    "Tver",
    "Magnitogorsk",
    "Surgut",
    "Bryansk",
    "Ivanovo",
    "Yakutsk",
    "Vladimir",
    "Simferopol",
    "Belgorod",
    "Nizhniy-Tagil",
    "Kaluga",
    "Chita",
    "Groznyy",
    "Volzhskiy",
    "Smolensk",
    "Podolsk",
    "Saransk",
    "Vologda",
    "Kurgan",
    "Cherepovec",
    "Orel",
    "Arhangelsk",
    "Vladikavkaz",
    "Nizhnevartovsk",
    "Yoshkar-Ola",
    "Sterlitamak",
    "Murmansk",
    "Kostroma",
    "Novorossiysk",
    "Tambov",
    "Himki",
    "Mytischi",
    "Nalchik",
    "Taganrog",
    "Nizhnekamsk",
    "Blagoveschensk",
    "Komsomolsk-na-Amure",
    "Petrozavodsk",
    "Korolev",
    "Shahty",
    "Engels",
    "Velikiy-Novgorod",
    "Lyubercy",
    "Bratsk",
    "Staryy-Oskol",
    "Angarsk",
    "Syktyvkar",
    "Dzerzhinsk",
    "Pskov",
    "Orsk",
    "Krasnogorsk",
    "Armavir",
    "Abakan",
    "Balakovo",
    "Biysk",
    "Yuzhno-Sahalinsk",
    "Odincovo",
    "Ussuriysk",
    "Prokopevsk",
    "Rybinsk",
    "Norilsk",
    "Volgodonsk",
    "Syzran",
    "Petropavlovsk-Kamchatskiy",
    "Kamensk-Uralskiy",
    "Novocherkassk",
    "Almetevsk",
    "Zlatoust",
    "Severodvinsk",
    "Hasavyurt",
    "Kerch",
    "Domodedovo",
    "Salavat",
    "Miass",
    "Kopeysk",
    "Pyatigorsk",
    "Elektrostal",
    "Maykop",
    "Nahodka",
    "Berezniki",
    "Kolomna",
    "Schelkovo",
    "Serpuhov",
    "Kovrov",
    "Neftekamsk",
    "Kislovodsk",
    "Bataysk",
    "Rubcovsk",
    "Obninsk",
    "Kyzyl",
    "Derbent",
    "Nefteyugansk",
    "Nazran",
    "Kaspiysk",
    "Dolgoprudnyy",
    "Novocheboksarsk",
    "Novomoskovsk",
    "Essentuki",
    "Nevinnomyssk",
    "Oktyabrskiy",
    "Ramenskoe",
    "Pervouralsk",
    "Mihaylovsk",
    "Reutov",
    "Cherkessk",
    "Zhukovskiy",
    "Dimitrovgrad",
    "Pushkino",
    "Artem",
    "Kamyshin",
    "Evpatoriya",
    "Murom",
    "Hanty-Mansiysk",
    "Novyy-Urengoy",
    "Seversk",
    "Orehovo-Zuevo",
    "Arzamas",
    "Noginsk",
    "Novoshahtinsk",
    "Berdsk",
    "Elista",
    "Sergiev-Posad",
    "Vidnoe",
    "Achinsk",
    "Tobolsk",
    "Noyabrsk"];

foreach ($cityNamesRus as $idx => $russianName) {
    $latinName = $cityNamesLatin[$idx];
    $rodPod = GeographicalNamesInflection::getCase($russianName, 'предложный');
    $pageRender = renderTemplate('index', array(
        'cityNameRus' => $russianName,
        'cityNameRusRod' => $rodPod
    ));

    /* Для отладки
    echo $pageRender;
    var_dump($pageRender);
    die();
    */

//    file_put_contents(strtolower($latinName) . ".php", $pageRender);
}